### ISSUE TITLE
It's doesn't work

### ISSUE THREAD

**Issue by dimka11** [lambdazy/lzy#664]
I have tried to get it works on two systems (Colab  and Ubuntu in WSL2) and get the same error:

```
dima@DESKTOP-5SK57UV:~$ lzy-terminal -u dimka11 -k ~/.ssh/private.pem
/home/dima/.local/lib/python3.9/site-packages/lzy/lzy-servant.jar
ERROR: transport error 202: gethostbyname: unknown host
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
```

Solutions from stackoverflow like https://stackoverflow.com/questions/50344957/java-jdb-error-transport-error-202-gethostbyname-unknown-host doesn't help.

```
dima@DESKTOP-5SK57UV:~$ java -version
openjdk version "1.8.0_352"
OpenJDK Runtime Environment (build 1.8.0_352-8u352-ga-1~18.04-b08)
OpenJDK 64-Bit Server VM (build 25.352-b08, mixed mode)
```

`Python 3.8 / 3.9`

**Comment by dimka11** [comment]
with official colab example I get:



```
INFO:<class 'lzy.api.v1.servant.bash_servant_client.BashServantClient'>:Getting bucket
2022-12-20 17:48:43,665 - <class 'lzy.api.v1.servant.bash_servant_client.BashServantClient'> - INFO - Getting bucket
---------------------------------------------------------------------------
BashExecutionException                    Traceback (most recent call last)
[<ipython-input-16-5c6178cc7075>](https://localhost:8080/#) in <module>
      1 env = LzyRemoteEnv()
----> 2 with env.workflow("training"):
      3     model = train(data_set)
      4 
      5 result = model.predict(data_set.data[0])

3 frames
[/usr/local/lib/python3.8/dist-packages/lzy/api/v1/servant/bash_servant_client.py](https://localhost:8080/#) in exec_bash(*command)
     45 
     46         if process.returncode != 0:
---> 47             raise BashExecutionException(
     48                 message=f"Process exited with code {process.returncode}\n STDERR: "
     49                 + str(err, encoding)

BashExecutionException: Process exited with code 127
 STDERR: bash: /tmp/lzy/sbin/storage: No such file or directory
If you are going to ask for help of cloud support, please send the following trace files: /tmp/lzy-log/
```
from custom_terminal_log:

```
2022-12-20 17:45:54.906 [INFO ] [main] LzyFsServer - Mounting LzyFs at /tmp/lzy.
2022-12-20 17:45:56.913 [INFO ] [main] LzyFsServer - Starting LzyFs gRPC server at fs://localhost:9998.
2022-12-20 17:45:58.516 [ERROR] [main] BashApi - Error while executing: --lzy-address https://api.lzy.ai:8899 --lzy-whiteboard https://api.lzy.ai:8899 --lzy-mount /tmp/lzy --host localhost --port 9999 --fs-port 9998 --private-key /root/.ssh/private.pem terminal
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[lzy-servant.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[lzy-servant.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[lzy-servant.jar:?]
	at ai.lzy.v1.LzyServerGrpc$LzyServerBlockingStub.getS3Credentials(LzyServerGrpc.java:857) ~[lzy-servant.jar:?]
	at ai.lzy.fs.LzyFsServer.<init>(LzyFsServer.java:98) ~[lzy-servant.jar:?]
	at ai.lzy.servant.agents.LzyAgent.<init>(LzyAgent.java:52) ~[lzy-servant.jar:?]
	at ai.lzy.servant.agents.LzyTerminal.<init>(LzyTerminal.java:52) ~[lzy-servant.jar:?]
	at ai.lzy.servant.commands.Terminal.execute(Terminal.java:84) ~[lzy-servant.jar:?]
	at ai.lzy.servant.commands.ServantCommandHolder.execute(ServantCommandHolder.java:36) ~[lzy-servant.jar:?]
	at ai.lzy.servant.BashApi.execute(BashApi.java:38) [lzy-servant.jar:?]
	at ai.lzy.servant.BashApi.main(BashApi.java:25) [lzy-servant.jar:?]
2022-12-20 17:46:56.571 [INFO ] [main] LzyFsServer - Mounting LzyFs at /tmp/lzy.
2022-12-20 17:46:58.578 [INFO ] [main] LzyFsServer - Starting LzyFs gRPC server at fs://localhost:9998.
2022-12-20 17:47:00.167 [ERROR] [main] BashApi - Error while executing: --lzy-address https://api.lzy.ai:8899 --lzy-whiteboard https://api.lzy.ai:8899 --lzy-mount /tmp/lzy --host localhost --port 9999 --fs-port 9998 --private-key /root/.ssh/private.pem terminal
io.grpc.StatusRuntimeException: UNKNOWN
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271) ~[lzy-servant.jar:?]
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252) ~[lzy-servant.jar:?]
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165) ~[lzy-servant.jar:?]
	at ai.lzy.v1.LzyServerGrpc$LzyServerBlockingStub.getS3Credentials(LzyServerGrpc.java:857) ~[lzy-servant.jar:?]
	at ai.lzy.fs.LzyFsServer.<init>(LzyFsServer.java:98) ~[lzy-servant.jar:?]
	at ai.lzy.servant.agents.LzyAgent.<init>(LzyAgent.java:52) ~[lzy-servant.jar:?]
	at ai.lzy.servant.agents.LzyTerminal.<init>(LzyTerminal.java:52) ~[lzy-servant.jar:?]
	at ai.lzy.servant.commands.Terminal.execute(Terminal.java:84) ~[lzy-servant.jar:?]
	at ai.lzy.servant.commands.ServantCommandHolder.execute(ServantCommandHolder.java:36) ~[lzy-servant.jar:?]
	at ai.lzy.servant.BashApi.execute(BashApi.java:38) [lzy-servant.jar:?]
	at ai.lzy.servant.BashApi.main(BashApi.java:25) [lzy-servant.jar:?]

```

**Comment by mrMakaronka** [comment]
Hello! 

Regarding the first problem: it seems that you have java 8 installed, but 17 is required. To install Java 17 run: `apt install -y openjdk-17-jdk`

BTW, in the next release we will remove java from dependencies.

Regarding the second problem: could you please show the contents of `lzy_err.txt`?

**Comment by mrMakaronka** [comment]
It seems that the issue was solved, so I am closing it.
